spring.application.name=api-vendas-bi

spring.datasource.url=jdbc:postgresql://localhost:5432/loja_bi
spring.datasource.username=postgres
spring.datasource.password=1533
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect